project:
  type: book
  resources:
    - /examples

book:
  title: "Slidecrafting"
  subtitle: "Making beautiful slides with reveal.js and Quarto"
  author: "Emil Hvitfeldt"
  date: "9/24/2025"
  chapters:
    - index.qmd
    - part: "Theming"
      chapters:
        - 10-minute.qmd
        - colors.qmd
        - fonts.qmd
        - sizes.qmd
        - scss.qmd
        - theme.qmd
    - part: "Content"
      chapters:
        - elements.qmd
        - layout.qmd
        - manual-code.qmd
        - asciicast.qmd
    - part: "Interactivity"
      chapters:
        - fragments.qmd
    - part: "Extensions"
      chapters:
        - letterbox.qmd
    - miscellaneous.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - styles.scss